packages:
  - playground
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.14.1
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@iconify-json/carbon': ^1.2.9
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/core': ^3.6.0
  '@shikijs/engine-javascript': ^3.6.0
  '@shikijs/engine-oniguruma': ^3.6.0
  '@types/adm-zip': ^0.5.7
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/node': ^22.15.30
  '@types/semver': ^7.7.0
  '@unocss/eslint-config': ^66.1.4
  '@unocss/eslint-plugin': ^66.1.4
  '@unocss/reset': ^66.1.4
  '@vitejs/plugin-vue': ^5.2.4
  '@vitest/expect': ^3.2.2
  '@vue-macros/volar': ^3.0.0-beta.14
  '@vueuse/core': ^13.3.0
  adm-zip: ^0.5.16
  bumpp: ^10.1.1
  chai: ^5.2.0
  chalk: ^5.4.1
  cson: ^8.4.0
  dotenv: ^16.5.0
  eslint: ^9.28.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fast-plist: ^0.1.3
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.3.0
  jsonc-parser: ^3.3.1
  lint-staged: ^16.1.0
  octokit: ^5.0.3
  ofetch: ^1.4.1
  ohash: ^2.0.11
  oniguruma-parser: ^0.12.1
  oniguruma-to-es: ^4.3.3
  p-limit: ^6.2.0
  pnpm: ^10.11.1
  rimraf: ^6.0.1
  semver: ^7.7.2
  simple-git: ^3.28.0
  simple-git-hooks: ^2.13.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.4
  unplugin-auto-import: ^19.3.0
  unplugin-vue-components: ^28.7.0
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-router: ^0.12.0
  vite: ^6.3.5
  vitest: ^3.2.2
  vue: ^3.5.16
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
  yaml: ^2.8.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
